version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - "./.htaccess:/var/www/html/.htaccess"
    container_name: shorturl
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: whatever
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: whatever

volumes:
  mysqldata: null